### PR TITLE
Support --hold and standard X11 geometry specifications.

### PR DESCRIPTION
**Pull request by gijsbers**
This is similar to other terminals like xterm, urxvt and mlterm.
Update man page and document all keyboard shortcuts.

### CODE REVIEW

**Comment by realh** [comment]
I think --hold could do with a bit of rework. Profiles have an option to exit, hold or restart, so if we're going to allow it to be overridden on the command line we should allow all three options eg
`--atexit=hold|close|restart`.

**Comment by realh** [comment]
I changed it a bit so that --atexit only applies to the terminal opened on the command line instead of overriding the entire profile, which could affect other terminals. Please can you check that it's working as expected before I release this.

**Comment by gijsbers** [comment]
Yes it works as intended, except for respawn. Roxterm respawns a shell, but not the command that was given. `roxterm --atexit=respawn --execute ps` should respawn the ps command, not the shell.

**Comment by realh** [comment]
That should be fixed now.

**Comment by gijsbers** [comment]
All fine for me.

**Pull request merged**
